# Generated by Django 4.1.2 on 2022-10-26 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(choices=[('0', '$5'), ('1', '$10'), ('2', '$20'), ('5', '$50')], default='0', max_length=1)),
                ('user', models.CharField(max_length=20)),
                ('pokemon', models.CharField(max_length=20)),
                ('blindfolded', models.BooleanField(default=True)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
