# Generated by Django 4.1.2 on 2022-10-26 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='blindfolded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='donation',
            name='pokemon',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
