# Generated by Django 4.1.2 on 2022-10-26 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_donation_blindfolded_alter_donation_pokemon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='amount',
            field=models.CharField(choices=[('05', '$5'), ('10', '$10'), ('20', '$20'), ('50', '$50')], default='05', max_length=2),
        ),
    ]
