# Generated by Django 4.1.2 on 2022-10-26 05:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_donation_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created'),
        ),
    ]
