# Generated by Django 4.1.2 on 2022-10-26 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_donation_created_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='created_date',
            new_name='created_time',
        ),
    ]
