# Generated by Django 4.1.2 on 2022-10-26 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_rename_created_date_donation_created_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='user',
            new_name='donator',
        ),
    ]
